Create cdkExecPolicy_tooling.yaml
awslabs/aws-dataall pull request #622
Opened 2023-08-02 23:23 UTC by mourya-33

CDK bootstrap policies for tooling account

### Feature or Bugfix
- Feature

### Detail
- Cloudformation stack to create least privilege iam policies for bootstrapping CDK to tooling and deployment accounts

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-10 20:13 UTC, noah-paige commented on deploy/cdk_exec_policy_tooling/cdkExecPolicy_tooling.yaml
> +                - !Sub 'arn:aws:codeartifact:*:${AwsAccountId}:domain/${EnvironmentResourcePrefix}-*'
Do we require all these resources for only the set of CloudFormation Actions listed in this statement?

2023-08-10 21:28 UTC, noah-paige requested changes
Some Additional Comments:

1. I needed the following additional permissions to have a successful deploy and delete (cross account CICD Deployment):

- [ ] cloudfront:UpdateDistribution
- [ ] ec2:DeleteNetworkAclEntry
- [ ] Ec2:DeleteNetworkAcl
- [ ] ec2:ReplaceNetworkAclAssociation
- [ ] Ec2:CreateNetworkAcl
- [ ] Ec2:CreateNetworkAclEntry
- [ ] Ec2:ReplaceNetworkAclEntry
- [ ] ecr:BatchGetImage
- [ ] ecr:GetDownloadUrlForLayer
- [ ] ECR + CodeArtifact cross account permissions (meaning I edited the resources section of Policy 4 `Sid:VisualEditor8` to include `ecr` and `codeartifact` resources for both the tooling and deployment account)

2.  I think we need to make the parameters more clear - for cross account deployments the way the current params are set up it would not assign the correct permissions

3.I think we should move this as part of the FAQ section in the GitHub Pages on “Deploying to AWS” and have a link there to download the `.yaml` for the execution policies. 

I think since we have not validated that this template works broadly for every configuration type in `cdk.json` and is more to be used as a “getting started” reference asset it makes sense to go in documentation rather than in the main code branch - but curious to hear you’re all thoughts on this @dlpzx @mourya-33

2023-08-11 20:18 UTC, mourya-33 commented on deploy/cdk_exec_policy_tooling/cdkExecPolicy_tooling.yaml
> +                  - 'SNS:GetTopicAttributes'
Done

2023-08-11 20:20 UTC, mourya-33 commented on deploy/cdk_exec_policy_tooling/cdkExecPolicy_tooling.yaml
> +                  - 'lambda:TagResource'
i missed to clean those up. Thank you. Removed them.

2023-08-11 20:50 UTC, mourya-33 commented on deploy/cdk_exec_policy_tooling/cdkExecPolicy_tooling.yaml
> +                  - !Sub 'arn:aws:cloudfront::${AwsAccountId}:distribution/*'
Done

2023-10-23 08:42 UTC, dlpzx commented
@mourya-33 this PR needs to be added to `v2m1m0` branch right? to be merged alongside the one with the commands to deploy it #819

2023-12-12 08:46 UTC, anmolsgandhi commented
@dlpzx This is pointed at modularization-main, do we need this PR or it is outdated now ?

2023-12-15 14:20 UTC, noah-paige commented
@mourya-33 - what is the status of this PR? There are still some pending comments above and we would need to re-test the execution policy for the latest set of features that can data.all support before we can review and merge this

Depending on the priority of this PR we can also close this for now and re-visit when some additional bandwidth is available - do let me know your thoughts?

cc: @anmolsgandhi @dlpzx

2023-12-21 16:28 UTC, noah-paige commented
Due to this PRs inactivity (last update on Aug 11) we will be closing it for now. Please re-open if it is required and additional changes are addressed, thanks

2023-12-21 16:28 UTC, closed without merging